import { GoogleGenAI } from "@google/genai";
import { NextResponse } from "next/server";

const EHR_PROMPT = `You are AfyaAI, generating a structured Electronic Health Record (EHR) based on an AI-assisted medical consultation.

Based on the conversation history provided, generate a professional EHR document in SOAP format:

# Electronic Health Record
**Generated by AfyaAI** | Date: [Current Date]

---

## Patient Information
- Patient ID: [Generate a unique ID]
- Date of Consultation: [Current Date/Time]
- Healthcare Provider: Community Health Worker (AI-Assisted)

## SOAP Notes

### Subjective (S)
- Chief Complaint
- History of Present Illness
- Patient-reported symptoms
- Duration and severity
- Relevant medical history mentioned

### Objective (O)
- Any observations noted during consultation
- Image analysis findings (if applicable)
- Vital signs (if reported)

### Assessment (A)
- AI-assisted triage level with justification
- Differential diagnosis considerations
- Risk factors identified

### Plan (P)
- Recommended interventions
- Follow-up timeline
- Referral recommendations
- Patient education points
- Medications suggested (if any)

---

## AI Confidence & Disclaimer
- Assessment confidence level
- ⚠️ This EHR was generated by an AI assistant and should be reviewed by a qualified healthcare provider.

Format the output as clean markdown. Be thorough but concise.`;

export async function POST(request) {
  try {
    const { messages, sessionId, triageLevel } = await request.json();

    if (!messages || messages.length === 0) {
      return NextResponse.json(
        { error: "No consultation messages provided" },
        { status: 400 },
      );
    }

    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey || apiKey === "your_gemini_api_key_here") {
      return NextResponse.json(
        {
          error:
            "Gemini API key not configured. Please add GEMINI_API_KEY to .env.local",
        },
        { status: 500 },
      );
    }

    const ai = new GoogleGenAI({ apiKey });

    // Build conversation summary
    const conversationText = messages
      .map((m) => `${m.role === "user" ? "CHW" : "AfyaAI"}: ${m.content}`)
      .join("\n\n");

    const currentDate = new Date().toLocaleDateString("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    });

    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: [
        {
          role: "user",
          parts: [
            {
              text: `${EHR_PROMPT}\n\nCurrent Date: ${currentDate}\nTriage Level from consultation: ${triageLevel || "Not determined"}\n\n--- CONSULTATION TRANSCRIPT ---\n\n${conversationText}`,
            },
          ],
        },
      ],
    });

    const ehrText = response.text || "";

    // Generate a brief summary
    const summaryResponse = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: [
        {
          role: "user",
          parts: [
            {
              text: `Summarize this medical consultation in one brief sentence (max 100 characters). Focus on the chief complaint and triage outcome:\n\n${conversationText}`,
            },
          ],
        },
      ],
    });

    const summary = summaryResponse.text || "AI consultation record";

    return NextResponse.json({
      ehr: ehrText,
      summary: summary.trim(),
      sessionId,
    });
  } catch (error) {
    console.error("EHR generation error:", error);
    return NextResponse.json(
      { error: error.message || "Failed to generate EHR" },
      { status: 500 },
    );
  }
}
